actors:
  coela:
    image_url: /images/actors/coela_head.png
    name: coela
    url: http://sns.example.com/alice
  tadasu:
    image_url: /images/actors/tadasu.jpg
    name: tadasu
  soh:
    image_url: /images/actors/soh.png
    name: soh
author: researchat
description: Podcast by researchers. Talking about Science, Technology, and Hobby.
description_long: サイエンス、テクノロジー、趣味などの話題を中心に、研究者が話すポッドキャスト番組
email: researchat@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-133831231-1
hashtag: researchatfm
itunes_podcast_url: https://researchat.fm/feed.xml 
keywords: research,science,technology,manga,games
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Researchat.fm
url: http://researchat.fm
