actors:
  coela:
    image_url: /images/actors/alice.png
    name: coela
    url: http://sns.example.com/alice
  tadasu:
    image_url: /images/actors/bob.png
    name: tadasu
    url: http://sns.example.com/bob
  sho-i:
    image_url: /images/actors/bob.png
    name: sho-i
    url: http://sns.example.com/bob
author: researchat
description: Podcast by researchers.
description_long: Podcast by researchers. Talking about science and technology.
email: researchat@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: researchatfm
itunes_podcast_url: https://researchat.fm/feed.xml
keywords: research,science,technology,manga,games
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Researchat.fm
url: http://researchat.fm
