actors:
  coela:
    image_url: /images/actors/coela_head.png
    name: coela
    url: https://twitter.com/DRZ400SM
  tadasu:
    image_url: /images/actors/tadasu.jpg
    name: tadasu
    url: https://snk-u.tumblr.com/
  soh:
    image_url: /images/actors/soh.png
    name: soh
    url: https://twitter.com/soh__i
author: researchat
description: Podcast by researchers. Talking about Science, Biotechnology, Programming and Hobby.
description_long: 生物学、バイオテクノロジー系の論文と技術紹介、プログラミングや趣味などの話題を中心に研究者が話すポッドキャスト番組
email: researchat@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-133831231-1
hashtag: researchatfm
itunes_podcast_url: https://itunes.apple.com/jp/podcast/researchat-fm/id1453892334?mt=2
keywords: research,science,technology,manga,games
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Researchat.fm
url: http://researchat.fm
