actors:
  coela:
    image_url: /images/actors/coela_head.png
    name: coela
    url: https://twitter.com/DRZ400SM
  tadasu:
    image_url: /images/actors/tadasu.jpg
    name: tadasu
    url: https://snk-u.tumblr.com/
  soh:
    image_url: /images/actors/soh.png
    name: soh
    url: https://twitter.com/soh__i
author: researchat
description: Researchat.fmは、バイオロジーの研究者3人がアツいと感じていることを自由に話すポッドキャスト番組です。
description_long: バイオロジーの研究者3人によるポッドキャスト番組です。東京-東海岸-山形をつなぎ、その時々アツいと感じたテーマについて研究・論文・技術・ゲーム・漫画など分野を問わず自由に話しています。
email: researchat@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-133831231-1
hashtag: researchatfm
itunes_podcast_url: https://itunes.apple.com/jp/podcast/researchat-fm/id1453892334?mt=2
keywords: research,science,technology,manga,games
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Researchat.fm
url: http://researchat.fm
